### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by StevenKnoop** [rchakode/hugo-mx-gateway#15]
Hi there,

I am trying to deploy this service to Google Cloud Go as docker container but I can't build the project locally.

![image](https://user-images.githubusercontent.com/5389509/166152363-a4ceb1d2-9285-4e1a-9ca4-1d365d9994b5.png)

Your help is greatly appreciated!

**Comment by rchakode** [comment]
Hi @StevenKnoop,
On Windows, the binary generated by Go is likely `hugo-mx-gateway.exe` (i.e. with .exe extension vs no extensionon on Linux), you may have to update the build command to force build for linux. 

```
env GOOS=linux GOARCH=amd64 make build
```

R.

**Comment by StevenKnoop** [comment]
Thank you for your reply @rchakode 

Sorry I didn't declare that I am using Windows CMD to build this image. I tried adding the ARG Variables to the Dockerfile but I get the same error except this time step(2/6) is cancelled.

![image](https://user-images.githubusercontent.com/5389509/166212903-1e43f80a-34f4-4633-a7c6-ac875b876659.png)


This is the updated Dockerfile:
```
FROM alpine:3.11.6

ARG GOOS="linux"
ARG GOARCH="amd64"

ARG RUNTIME_USER="mxgateway"
ARG RUNTIME_USER_UID=4583

RUN addgroup -g $RUNTIME_USER_UID $RUNTIME_USER && \
    adduser --disabled-password --no-create-home  --gecos "" \
    --home /app --ingroup $RUNTIME_USER --uid $RUNTIME_USER_UID  $RUNTIME_USER
	
COPY entrypoint.sh bin/hugo-mx-gateway  LICENSE /app/
COPY templates /app/templates

RUN chown -R $RUNTIME_USER:$RUNTIME_USER /app

WORKDIR /app
ENTRYPOINT ["sh", "./entrypoint.sh"]
```
Your input would be appreciated.

**Comment by rchakode** [comment]
Check the binary generated in the `bin` directory after the build

**Comment by StevenKnoop** [comment]
The bin folder was always empty after builds.

Mr @ruanbekker was a great help, he supplied me with the following information to successfully build the image locally on Windows.

Add these variables to your environment(Dockerfile):
```
ARG GOOS="windows"
ARG GOARCH="amd64"
ARG GO111MODULE="on"
```

And run this command to generate the binary in the bin folder
`go build -a -tags netgo -ldflags '-w="-static"' -o .\bin\hugo-mx-gateway -v -buildvcs=false`

Thank you to @rchakode, @ruanbekker and @sn for all the help
