### ISSUE TITLE
No docker image at docker hub

### ISSUE THREAD

**Issue by sr-verde** [rchakode/hugo-mx-gateway#4]
Hey,

I would like to create a contact form for a Hugo website. Is this software still under developement? There is no `rchakode/hugo-mx-gateway:latest` image available although your docs tell me to use it.

Best!

**Comment by rchakode** [comment]
Hi @sr-verde ,
Thank you to have reported this. 
Due to a typo the image  was not pushed at the right repo. 
It shall be fixed now.

**Comment by sr-verde** [comment]
Wonderful! An thanks for the really fast response.
