### ISSUE TITLE
Feature request: documentation - how to create a docker for linux/arm/v7

### ISSUE THREAD

**Issue by nodurah** [rchakode/hugo-mx-gateway#5]
Hello rchakode,

to deploy this project on a raspbian (linux/arm/v7) platform it would be wonderful, if there would be any documentation how to create a docker. Otherwise a wonderful project that fills a gap!

Kind regards, nodurah

**Comment by rchakode** [comment]
Hi @nodurah 
If I understand your need, you want to build a Docker image for rasbian. Right?
To do so, proceed as follows:

- compile the Go code for raspbian `env GOOS=linux GOARCH=arm GOARM=$ARM_VERSION go build`
- Then edit the first line of the Dockerfile and set the base image to a raspian-compatible image https://github.com/rchakode/hugo-mx-gateway/blob/2460c7f147649fcd1d3ed236befb44130e6ea598/Dockerfile#L1
- Finally build the Docker image `docker build .`

Let me know if this help.

R.

**Comment by nodurah** [comment]
Hello @rchakode 
Thanks for the quick advice. That was exactly what I was looking for. After installing go on the host system I already had compiled the go files, so I started at step two.
Unfortunately the curl command with https returns an error code. The unencrypted version seems to work fine.
```
curl https://127.0.0.1:8080/
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
When I try to run the form just with an http connection I get a return status 

`{"status": "ok"}` 

but I don't get the redirected static page mentioned in the documentation. Probably I'm missing something here.

Cheers nodurah

**Comment by rchakode** [comment]
Hi,
Happy to know that the comments help.

The default endpoint `/` is handle heathcheack, no redirection hence. 
The redirection occurs when you call the `/sendmail` endpoint (follow this link to get detail about the integration https://github.com/rchakode/hugo-mx-gateway#use-the-built-in-form-for-hugo).

Let me know if this helps.

**Comment by nodurah** [comment]
Hello,
sorry, I overread (several times) the "/sendmail" in the documentation. The backend is now called with the correct URL but I think it is not working correctly as there seems to be still the issue with the SSL /TLS encryption. Is there any way to get a more detailed debug log within the docker container of the programm?
Cheers

**Comment by rchakode** [comment]
Hello,
I see the point, in the documentation it was mentioned `https` but by default the Docker container is configured in http mode (it's fixed now). 

Sorry, use `http://localhost` as base URL. 
Otherwise you can get the logs of the container for more details (`docker logs <container>`).

**Comment by rchakode** [comment]
I'll close this issue.

**Comment by nodurah** [comment]
Yes, the issue can be closed! Thanks again for the quick help - cheers!
