### ISSUE TITLE
Don't use email of client as sender

### ISSUE THREAD

**Issue by dorianim** [rchakode/hugo-mx-gateway#6]
Hi,

Over here: https://github.com/rchakode/hugo-mx-gateway/blob/73a3eb02669dce7e5edec7bd4ef76c4d8c51aad7/sendmail.go#L264
You set the email address from the form as the sender address. This is a problem with most mail servers, as they allow only the actual mail address of the user as the sender address.

Could you add an option to change that behavior?

Best Regards,
Dorian

**Comment by rchakode** [comment]
Hi, 
Thanks to suggest this enhancement.
We will take that into account asap.

Regards,
R.

**Comment by rchakode** [comment]
hi @dorianim,
The latest release does not longer use the form email as sender. Instead, the `CONTACT_REPLY_EMAIL` parameter is always used.

**Comment by dorianim** [comment]
Hi @rchakode 

Thank you very much.
